name: Build and Deploy
on:
    push:
        branches: ['main']
jobs:
    deploy:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Deploy Strapi APP
              uses: appleboy/ssh-action@v0.1.10
              with:
                  host: ${{secrets.SSH_SERVER}}
                  key: ${{secrets.SSH_KEY}}
                  username: ${{secrets.SSH_USERNAME}}

                  script: |
                      if cd condelivery; then
                          git reset --hard origin/main
                          git pull
                          # Install deps
                          yarn install --frozen-lockfile
                          # Build the thing
                          yarn build
                          # Spin up the server
                          sh scripts/start.sh
                      else
                          git clone https://github.com/LuisHCK/condelivery-strapi condelivery
                          cd app
                          # Install deps
                          yarn install --frozen-lockfile
                          # Build the thing
                          yarn build
                          # Spin up the server
                          sh scripts/start.sh
                      fi
